id: IC3C528CF
ocr_import_info:
  timestamp: '2023-09-27T04:30:59.562478+00:00'
  batch_id: batch-3f0f
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-27 04:37:38.957354+00:00
last_modified: 2023-09-27 04:37:38.957361+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W4998
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4998
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤྱོད་འཇུག་ཤེར་ལེ་བརྒལ་ལན་ཉིན་བྱེད་སྣང་བ།
  languages:
  - bo
  author: འཇུ་མི་ཕམ་འཇམ་དབྱངས་རྣམ་རྒྱལ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.934662372595081
  ocr_word_median_confidence_index: 0.984364
bases:
  I1CZ984:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ984
      total_pages: 96
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ984.txt
    statistics:
      ocr_word_median_confidence_index: 0.984364
      ocr_word_mean_confidence_index: 0.934662372595081
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
